<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"员工管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"部门管理",
					    "menuJump":"列表",
					    "tableName":"dictionaryBumen"
					}
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"岗位类型管理",
					    "menuJump":"列表",
					    "tableName":"dictionaryGangwei"
					}
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"职务类型管理",
					    "menuJump":"列表",
					    "tableName":"dictionaryZhiwu"
					}
			    ],
			    "menu":"人事管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"客户信息管理",
			            "menuJump":"列表",
			            "tableName":"kehu"
			        }
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"跟进方式管理",
					    "menuJump":"列表",
					    "tableName":"dictionaryGenjin"
					}
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"客户级别管理",
					    "menuJump":"列表",
					    "tableName":"dictionaryJibie"
					}
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"客户来源管理",
					    "menuJump":"列表",
					    "tableName":"dictionaryLaiyuan"
					}
			    ],
			    "menu":"客户信息管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"产品信息管理",
                        "menuJump":"列表",
                        "tableName":"canpin"
                    }
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"产品类型管理",
					    "menuJump":"列表",
					    "tableName":"dictionaryCanpin"
					}
                ],
                "menu":"产品信息管理"
            }
            ,{
                "child":[
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"合同信息管理",
					    "menuJump":"列表",
					    "tableName":"hetong"
					}
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"订单信息管理",
					    "menuJump":"列表",
					    "tableName":"dingdan"
					}
                ],
                "menu":"合同订单管理"
            }
			,{
			    "child":[
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"发票信息管理",
					    "menuJump":"列表",
					    "tableName":"fapiao"
					}
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"收款信息管理",
					    "menuJump":"列表",
					    "tableName":"shoukuan"
					}
					,  
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"发票类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFapiao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"支付方式管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhifu"
                    }
			       
			    ],
			    "menu":"财务管理管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"新闻信息管理",
					    "menuJump":"列表",
					    "tableName":"xinwen"
					}
					,
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "修改",
					        "删除"
					    ],
					    "menu":"站内信息管理",
					    "menuJump":"列表",
					    "tableName":"zhannei"
					}
                ],
                "menu":"信息中心管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"客户信息管理",
			            "menuJump":"列表",
			            "tableName":"kehu"
			        }
			    ],
			    "menu":"客户信息管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"产品信息管理",
	                    "menuJump":"列表",
	                    "tableName":"canpin"
	                }
	            ],
	            "menu":"产品信息管理"
	        }
	        ,{
	            "child":[
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"合同信息管理",
					    "menuJump":"列表",
					    "tableName":"hetong"
					}
					,
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"订单信息管理",
					    "menuJump":"列表",
					    "tableName":"dingdan"
					}
	            ],
	            "menu":"合同订单管理"
	        }
			,{
			    "child":[
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"发票信息管理",
					    "menuJump":"列表",
					    "tableName":"fapiao"
					}
					,
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"收款信息管理",
					    "menuJump":"列表",
					    "tableName":"shoukuan"
					}
			       
			    ],
			    "menu":"财务管理管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
					,
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"新闻信息管理",
					    "menuJump":"列表",
					    "tableName":"xinwen"
					}
					,
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"站内信息管理",
					    "menuJump":"列表",
					    "tableName":"zhannei"
					}
	            ],
	            "menu":"信息中心管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"员工",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
